pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - base=main
    actions:
      merge:
        method: merge
      label:
        add: ['hacktoberfest-accepted']
