pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - check-success=Travis CI - Pull Request
      - base=main
    actions:
      merge:
        method: merge
      label:
        add: ['hacktoberfest-accepted']
